name: bybullet
description: "Reminder by Bullet"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  time_picker_spinner: ^1.0.0

  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.6


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - lib/assets/icons/write_icon.svg
    - lib/assets/icons/enter_icon.svg
    - lib/assets/icons/check_icon.svg
    - lib/assets/icons/calendar_icon.svg
    - lib/assets/icons/bin_icon.svg
    - lib/assets/icons/task_bullet.svg
    - lib/assets/icons/completed_bullet.svg
    - lib/assets/icons/priority_bullet.svg
    - lib/assets/icons/memo_bullet.svg
    - lib/assets/icons/migrated_bullet.svg
    - lib/assets/icons/logo.svg

  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/Pretendard-thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Pretendard-Medium.ttf
          weight: 400
        - asset: lib/assets/fonts/Pretendard-Regular.ttf
          weight: 500
        - asset: lib/assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Pretendard-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_logo.png"

flutter_native_splash:
  color: "#F9F9F9"
  image: lib/assets/icons/splash_icon.png
  android: true
  ios: true